name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: prod
        type: choice
        options:
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::723157092580:role/Github-actions-terraform-role
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform -chdir=envs/dev init
      - run: terraform -chdir=envs/dev plan
      - run: terraform -chdir=envs/dev apply -auto-approve


  deploy-prod:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::723157092580:role/Github-actions-terraform-role
          aws-region: ap-south-1

      - uses: hashicorp/setup-terraform@v3

      - run: terraform -chdir=envs/prod init
      - run: terraform -chdir=envs/prod plan
      - run: terraform -chdir=envs/prod apply -auto-approve